-- Step 4: DLQ 컬럼 추가
-- MySQL용
ALTER TABLE OUTBOX_TB ADD COLUMN RETRY_COUNT INT DEFAULT 0;
ALTER TABLE OUTBOX_TB ADD COLUMN LAST_ERROR_MSG VARCHAR(500);
ALTER TABLE OUTBOX_TB MODIFY COLUMN STATUS VARCHAR(20) DEFAULT 'UNPROCESSED';

-- Oracle용
-- ALTER TABLE OUTBOX_TB ADD (RETRY_COUNT NUMBER(10) DEFAULT 0);
-- ALTER TABLE OUTBOX_TB ADD (LAST_ERROR_MSG VARCHAR2(500));
-- ALTER TABLE OUTBOX_TB MODIFY STATUS VARCHAR2(20) DEFAULT 'UNPROCESSED';
